UKHomeOffice/hocs-workflow

src/main/resources/processes/MPAM.bpmn
Fix. Stop remembering the last update user when leaving any Escalated stage.
=> HOCS-1801 : case restored to previous Triage owner when deescalated

build.gradle, src/main/java/uk/gov/digital/ho/hocs/workflow/application/CamundaProcessEngineConfiguration.java
- updating default id generation (DBIdGenerator) in favor of StrongUuidGenerator
as it is the one recommended in camunda docs
- Adding java-uuid-generator dependency as it is required for StrongUuidGenerator
After investigation is has been discovered that intermittent issues are caused
by optimistic lock exception that occur when Camunda uses default DbIdGenerator on
more than 1 service (single db and multiple services)
More details here:
https://docs.camunda.org/manual/7.9/user-guide/process-engine/id-generator/#the-uuid-generator
=> HOCS-1812 - WCS case closed with no apparent reason

src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/SchemaDto.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/SchemaDtoBuilder.java, src/main/java/uk/gov/digital/ho/hocs/workflow/domain/model/forms/HocsSchema.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java
- added new json object at schema (screen) level. This can be used to store a lot of frontend specific config.
Currently it is only used to hold validationSuppressor configuration.
=> HOCS-1862 - Ability to suppress validation on certain actions

src/main/resources/processes/MPAM_CREATION.bpmn
At present when you get to the MPAM Correspondents Details page you cannot go back to correct any incorrect information at the creation stage. This pull request adds the functionality to go back to the creation screen to amend any further details.
=> HOCS-2101: add backwards functionality to MPAM Correspondents Details

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
This commit adds a check immediately prior to assigning a team based on
a selected topic at (e.g.) markup stage. If the team is inactive, it
doesn't assign a team at all.
As far as I can tell, that means the case gets sent to the default team
(that is, DCU's central team).
This has the side-effect of meaning that in the UI on the override
("Answering") screen the missing team will show up as an empty field.
However, this is quite an edgey edge-case that should rarely surface, so
I think that's fine for now.
This commit also adds tests; previously the method had no coverage.
=> HOCS-2191 Don't assign team from topic if inactive

src/main/resources/processes/MPAM_DISPATCH.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_QA.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
Corrections made to the calls made from bpmn diagrams to the bpmn Service method to create case notes.
The call to createCaseNote from bpmn diagrams had the wrong parameters, now fixed.
=> HOCS-2019 : correct bpmn calls to bpmn service to create case note

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/main/resources/processes/MPAM_TRIAGE_REQUESTED_CONTRIBUTION.bpmn
Remove the saving of a contribution note as that needs to be moved within the hocs-casework on contribution note addition. 
Fix to MPAM_TRIAGE bpmn to go back to contribution requested if escalated at that stage.
Unallocate case when going into contribution requested stage in MPAM Triage.
=> HOCS-2274: Change to workflow to adapt to new Somu flow

src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraft.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriage.java
Changing a case from reftype "Ministerial" to "Official" clears ministerial only data values: MinSignOffTeam, Addressee
At both Triage and Draft.
Now with Camunda unit tests!
=> HOCS-2296 : change to Official clears Ministerial data, fix

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_DRAFT_REQUESTED_CONTRIBUTION.bpmn, src/main/resources/processes/MPAM_TRIAGE_REQUESTED_CONTRIBUTION.bpmn
Update MPAM Draft to allow for Multiple Contribitions. This has involved removing the saving of the note in the stage as the values are no longer used at that point. Also encompasses a fix to go back to MPAM Draft Requested Contributions stage if the user escalates and completes the escalation.
=> HOCS-2274: Update MPAM Draft to allow for MC 

src/main/resources/processes/MPAM_DISPATCH.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_PO.bpmn, src/main/resources/processes/MPAM_QA.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDispatch.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraft.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMPo.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMQa.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriage.java
Set new "Rejected" value when moving back from: Draft, QA (to Triage), QA (to Draft), PO, Dispatch.
Clear new "Rejected" value when moving from: Triage->Draft, Draft->QA, Draft->Dispatch (B-Ref only).
Renamed some Camunda boxes to improve readability of workflow unit tests for each of the eight scenarios above.
=> HOCS-2026 : new workstack "Rejected" column

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DRAFT_REQUESTED_CONTRIBUTION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM_DRAFT_REQUESTED_CONTRIBUTION.java
After coming out of draft contribution requested a screen now shows that allows the user to be able to either unallocate a case or retain ownership. This change modifies the MPAM_DRAFT_REQUESTED_CONTRIBUTION workflow to show the screen and the MPAM workflow to action the unallocation.
=> HOCS-2121: Retain or unallocate after draft contributions

.drone.yml
As a result of the change to allow for workflow epic builds we are currently tagging the wrong project. This change rectifies this to be workflow instead of casework.
=> Drone tagging for installing docker image using casework

.drone.yml
Project name was incorrectly spelt worflow instead of workflow in drone.yml `install-docker-image-latest`step. 
This change ensures that the pipeline can be ran successfully.
=> Fix name of project incorrect - was worflow and not workflow

src/main/resources/processes/MPAM.bpmn
Update the all variable placement to allow for the further down blanking out of RefTypeStatus and BusAreaStatus to take affect. This was changed previously incorrectly.
=> HOCS-2364: Update variable placement

src/main/resources/processes/MPAM_TRANSFER.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTransfer.java
At present we don't have a way of handling the back button
when returning from the MPAM_UPDATE_BUS_AREA_ON_TRANSFER_EXIT 
screen. This change adds the workflow requirements to return to
the previous screen.
=> HOCS-2405: handle backwards from misallocations screen

src/main/resources/processes/MPAM.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java
Added an activity to clear the userid (unallocate) when transferring cases back to transfer stage from triage and draft stages.
=> HOCS-2406 unallocate user when moving back to transfer stage

src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraft.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraftEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriage.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriageEscalate.java
Changing a case from reftype "Ministerial" to "Official" clears ministerial only data values: MinSignOffTeam, Addressee
At both Triage Escalated and Draft Escalated.
=> HOCS-2296 : change to Official clears Ministerial data inc Escalated, fix

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
Fix for when an override markup team has been disabled and the case is then updated with no override team selected. The case should no longer have an override team selected and the _correct_ initial team(s) should be selected.
- Branched from #377 as changes to the `updateTeamSelection` meant I could implement a simpler solution.
- Added a check into `updateTeamSelection` to see if Override Teams are inactive. If they are, remove them by setting null.
- Add tests to `BpmnServiceTest`.
=> HOCS-2283 - Fix markup teams being updated when team disabled

build.gradle, src/main/resources/processes/DCU_DTEN.bpmn, src/main/resources/processes/DCU_MIN.bpmn, src/main/resources/processes/DCU_TRO.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN_DTEN_TRO_CallActivityVariables.java, src/test/java/uk/gov/digital/ho/hocs/workflow/util/CallActivityTestUtil.java, src/test/java/uk/gov/digital/ho/hocs/workflow/util/CallActivityVariable.java
Changes to take into account any overridden drafting or po team, when associating with work stacks. 
Added a new test approach for Call activity variable checking.
=> Hocs 2471 - draft/po team override

src/main/resources/processes/MPAM_TRANSFER.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTransfer.java
This bug was caused by Ministerial Response and Urgency fields being made conditional by ticket 2394. The fix is to clear business area on leaving the transfer stage this will redisplay the missing fields.
Process tests for this functionality and other paths have been added, we now have 93% test coverage on the transfer stage.
=> HOCS-2449 clear business area on leaving transfer stage

.drone.yml
This change implements the necessary changes 
to use Drone V1 as V0.8 is going to be deprecated. 
Changes include :
- Split build and deploy into two pipelines
- Removed pull request checks
- Changed to push to build_XXX instead of build-XXX
- Added commit sha tag
- Switched to using KUBE_TOKEN as defined in Drone 
rather than the kube repo
- Added acyclic dependency graph for asynchronous build steps
- Made a QA release always release to both QA environments 
consolidated build steps where possible
- Split build step into build and test step
=> HOCS-2641: migrate from drone 0.8 to 1

src/main/resources/processes/FOI.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI.java
This ticket adds the initial top level bpmn digram for FOI workflow. It does nothing but close a created case. Further stages shall be added to this diagram.
A process test is also included.
=> HOCS-2539 : add top level bpmn digram for FOI

src/main/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClient.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClientTest.java
New feature where Camunda's User Task's form key can be used to store the screen names.
See https://collaboration.homeoffice.gov.uk/display/HOCS/Camunda+Improvements#CamundaImprovements-Usingformkeytostoretheformnames
If a Form Key is specified for a user task it will be used as the source for the screen name.
Otherwise the existing behaviour of looking for the screen name in the process variable is maintained.
=> Support 'Form Key' as a source for screen names

src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraftEscalate.java
A regression was introduced in HOCS-2311 that stopped the PutOnCampaign DraftStatus to no longer work. This change reverts a partial unintended change and adds test to stop this happening again.
=> HOCS-2747: fix draft put on campaign

.drone.yml
This adds a step to Drone that fires on push to the FOI epic branch,
which triggers a deployment to the hocs-gamma environment.
Previously we were deploying manually to hocs-gamma, and using a fixed
branch-based tag, which was causing inconsistencies and confusion. Here
we deploy a tag based on the Drone build number, which is easier to
track. If we wanted, we could deploy using the SHA hash for a similar
effect.
=> HOCS-2885 Automatically deploy to gamma on push

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
When a case has an override team set and is then later changed to a 
`FAQ Response` this override team is not wiped. This leads to the 
case being placed in an incorrect team. This change wipes the value 
of the `OverrideDraftingTeamUUID` and 
`OverrideDraftingTeamName`.
=> HOCS-2915: wipe override draft team

src/main/java/uk/gov/digital/ho/hocs/workflow/application/CamundaProcessEngineConfiguration.java, src/main/resources/processes/MPAM/MPAM_UPDATE_ENQUIRY_SUBJECT_REASON.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMCommonTests.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriage.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriageEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/mpam/MPAMUpdateEnquirySubjectReason.java
This change encompasses the following changes: 
- Now load all bpmn files in the processes folder and any subfolder. Allowing for seperation of workflows under business unit.
- Pull out the Update Enquiry Subject and Reason from MPAM Triage and put into it's own workflow. This is then reused in the MPAM Triage Esclate.
=> HOCS-2923: allow enquiry reason subject change

src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResource.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/UpdateCaseValueRequest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResourceTest.java
Currently when a team is moved outside a workflow, the internal 
representation of the case is not update-able. This change adds an 
endpoint that allows for the updating of the data. This endpoint is 
protected by the `@Authorised` annotation for users with write 
permissions.
=> HOCS-2975: add update case value endpoint

src/main/resources/processes/MTS.bpmn, src/main/resources/processes/MTS_DATA_INPUT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/mts/MTS.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/mts/MTS_DATA_INPUT.java
For new MTS cases we no longer want the ability to put the case on 
hold. This changes works in conjunction with the data change that 
results in action item no longer existing that can put a case on hold.
We no longer allow the user to save changes as pending, so new 
cases should not have this option available on the diagram.
=> HOCS-2762 remove on hold option

src/main/resources/processes/WCS.bpmn
As we are currently changing the internal representation of the data, 
we need to pull this out of the stage when we finish one. As we 
change it for the stage level we can assign the outer variable to the 
same.
Currently when a team is moved outside a workflow, the internal 
representation of the case is not update-able. This change adds an 
endpoint that allows for the updating of the data. This endpoint is 
protected by the `@Authorised` annotation for users with write 
permissions.
=> HOCS-2739: moving WCS team update case

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/infoclient/dto/StageTypeDto.java, src/main/resources/processes/FOI_ACCEPTANCE.bpmn, src/main/resources/processes/FOI_ALLOCATION.bpmn, src/main/resources/processes/FOI_DRAFT.bpmn, src/main/resources/processes/FOI_QA.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_ACCEPTANCE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_ALLOCATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DATA_INPUT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_QA.java
Update case notes to display clearly whether they refer to a case allocation or a case rejection.
Allocation notes should show:
The team which made the allocation
The team the case was allocated to
The stage at which the allocation took place
Rejection notes should show:
The team who rejected the case
The stage at which the rejection took place
=> HOCS-3064: improve allocation notes by adding additional information

src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/StageDto.java, src/main/java/uk/gov/digital/ho/hocs/workflow/domain/model/forms/HocsForm.java, src/main/java/uk/gov/digital/ho/hocs/workflow/security/UserPermissionsService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClientTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/security/UserPermissionsServiceTest.java
If at the end of a stage the user is a member of the team that handles the case at the next stage, then the case might want to be be allocated to them automatically and displayed on screen, instead of just going to the workstack.
When the workflow service - updateStageForward() - detects that the end of a stage is reached - in getStage() - it checks if the current user is on the team for the next stage. If they are the user is allocated to that case, and data relating to the new stage is returned to the front end.
The front end code detects if the stageId has changed, and uses that instead when it redirects.
The feature can be turned on by setting a process variable in the Camunda diagram.
=> HOCS-3193 Sticky Cases

src/main/java/uk/gov/digital/ho/hocs/workflow/security/RestResponseSecurityExceptionHandler.java
The frontend is using the FORBIDDEN and UNAUTHORISED response status' to drive its logic. 
The workflow endpoints annotated with @Allocated logs error messages when called if the user or team is not currently allocated.
We either lower the logging to WARN (this ticket) or redesign the frontend logic to not rely on the error status'
=> HOCS-3278 - Lowering logging level.

src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/CreateCaseworkCorrespondentRequest.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/AddressDto.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/CreateCaseworkCaseResponse.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/GetCorrespondentResponse.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/GetCorrespondentsResponse.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java
Adding in the ability for a user to enter the correspondent details when creating a case, this includes showing the correct details depending on the correspondence type.
=> HOCS-3289 Add Correspondent Details to Case Creation Step

src/main/resources/processes/MPAM_QA_CLEARANCE_REQ.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMQaClearanceRequest.java
Add the rejection allocation note service task when rejecting back to
the MPAM Draft stage from the MPAM QA Secretariat Clearance page.
=> HOCS- 3776: rejection note from MPAM QA Secretariat Clearance

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_PO_APPROVED_LOCAL_DISPATCH.bpmn, src/main/resources/processes/MPAM_PO_APPROVED_MIN_DISPATCH.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMPoApprovedLocalDispatch.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMPoApprovedMinDispatch.java
Remove the backwards action from the MPAM Private Office Local and
Ministerial dispatch workflows as they are no longer required.
=> HOCS-3752: remove backwards action

src/main/resources/processes/SMC_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/SMC_TRIAGE.java
Currently, there isn't a path for pending in the SMC_TRIAGE model. This
means that the case moves to draft instead of staying in triage. This
change adds this path and the required test coverage.
=> HOCS-3987: Add pending path to SMC_TRIAGE

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java
Currently, there is a use case of the old method that requires 6
parameters. This change reintroduces this and sends null as the 7th
parameter. A new null check has been added to the 7th method parameter.
=> HOCS-4046: move unit and wrap in null

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
added check for null field when adding case notes. Null field is replaced by empty string and error logged as this should not really be happening.
=> HOCS-4081 add check for null field when adding case notes

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
I have altered the way updates to existing case notes are handling when the text value is null. Previously the null value was replaced with an empty string but that leads to blank case notes in the timeline so any null values are now ignored and the case note is unaltered.
=> HOCS-4081 update to null case note issue

.drone.yml
When pushing to main the pipeline is thought to be running out of
resources and failing on the deployment to the dev environments. This
change doubles the default to see if this is the case.
=> Fix: pipeline resource allocation

.drone.yml
This change incorporates a reversion on the resources allocated to the pipeline as they aren't required. Alongside this, a correction to the directory we `cd` into in the `deploy to *dev` steps to use the `kube` has been applied.
=> HOCS-4030: fix pipeline directory

kube/kd/deployment.yaml, src/main/resources/application.properties
during testing the compression it was observed that increasing the connection pool limit did decrease the response times for both casework and workflow services
=> Hocs-3430 disable compression

build.gradle, src/integration-test/resources/application.properties, src/main/java/uk/gov/digital/ho/hocs/workflow/HocsWorkflowApplication.java, src/main/java/uk/gov/digital/ho/hocs/workflow/application/RestHelper.java, src/main/resources/application.properties
As part of the investigation it was determined that the application was failing to create new threads for the retry code, we have given the pods more memory but we don't believe we need to use @Retry at all - we prefer to fail fast.
=> HOCS-4312 - Remove the Retry annotation

src/main/resources/processes/COMP2_CCH_RETURNS.bpmn, src/main/resources/processes/COMP_CCH_RETURNS.bpmn, src/test/diffs/COMP_CCH_RETURNS-COMP2_CCH_RETURNS.diff, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP_CCH_RETURNS.java
At the moment when a case is transferred via CCH returns the CompType is
not changed. This change adds an activity to the COMP and COMP2 CCH flow
that updates the CompType before transfer.
=> HOCS-4238: Update CompType when transferring case

src/main/resources/processes/BF.bpmn, src/main/resources/processes/BF_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/BF_ESCALATE.java
Add the sequence flows for cases that are being sent through the BF
escalation process. For cases that come through there is the option to
send the case to Triage or Draft. This direction happens through the
main BF process diagram is handled through an output process variable.
=> HOCS-4055: add case flow for BF escalated cases

build.gradle, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowConstants.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_REGISTRATION.bpmn, src/test/diffs/COMP-COMP2.diff, src/test/diffs/COMP_REGISTRATION-COMP2_REGISTRATION.diff, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP_REGISTRATION.java
This changes support the requirement for a user to be able to close a
WebForm case as early as possible if it's not deemed valid. This is done
through a check if the channel is specified as WebForm and then shows a
validation screen within COMP_REGISTRATION. The outcome of this screen
is then propagated up to the COMP workflow to complete the case as
required.
WIP change for closing Webform cases earlier in the pipeline. This
contains the core logic that works - the other parts (form design)
should be easily alterable).
=> HOCS-4440: WebForm complaints allows early closure

README.md, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowConstants.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/resources/processes/COMP_REGISTRATION.bpmn, src/test/diffs/COMP_REGISTRATION-COMP2_REGISTRATION.diff, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP_REGISTRATION.java
To better support strictly WebForm cases for COMP in the future, 
the driving process variable has been altered to the non-modifiable
variable called `XOriginatedFrom`. 
It also supports the passing through the received data to the case 
data if it originates from the UKVI WebForm.
=> HOCS-4462: alter driving variable for WebForm case

src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/main/resources/processes/SHARED/COMPLAINT_CORRESPONDENT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/shared/COMPLAINT_CORRESPONDENT.java
Add the process for a shared complaint correspondent flow. This flow
shows takes a user specified screen for input and invalid alongside the
case to validate correspondents to ensure the primary correspondent is a
Complainant.
Add the shared correspondent flow to the POGR_REGISTRATION screen.
=> HOCS-4703: add correspondents flow for POGR

src/main/resources/processes/TO_DRAFT.bpmn, src/main/resources/processes/TO_QA.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_QA.java
Added a fix to QA and Draft stages to allow cases to transfer to Stop List and Campaign and reject to earlier stages.
=> HOCS-4761 add fix to allow case to move correctly from QA and Draft

src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/main/resources/processes/SHARED/COMPLAINT_CORRESPONDENT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/shared/COMPLAINT_CORRESPONDENT.java
After the Data Input stage has completed if you go backwards then a
different screen should be shown. This is to enable a restriction
whereby the Business Area cannot be changed.
After checking if the primary correspondent is of type `COMPLAINANT` a
default backward flow is added whereby if `validCorrespondents` is not
true.
=> HOCS-4773: add backwards flow post data input

src/main/resources/processes/POGR/POGR.bpmn, src/main/resources/processes/POGR/POGR_GRO.bpmn, src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn, src/main/resources/processes/POGR/POGR_HMPO.bpmn, src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn, src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Changes to the POGR and the POGR_REGISTRATION flows to support the
movement of a case through to the triaging stages. For GRO cases a new
screen is shown that allows for the selection of a triaging team.
=> HOCS-4632: support GRO triaging allocation

src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
The telephone response flow from draft now supports a radio option
whereby a 'No' value drives it back to the previous screen.
=> HOCS-4635: change the telephone flow to use radio

src/main/java/uk/gov/digital/ho/hocs/workflow/client/documentclient/DocumentClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/documentclient/dto/DocumentDto.java
Move away from custom endpoint to help docs service handle database access in a consistent way
=> HOCS-5161: move away from custom 'name' endpoint

src/main/java/uk/gov/digital/ho/hocs/workflow/client/documentclient/dto/DocumentDto.java
Bug fix for the DocumentDTO causing problems with Jackson object mapping when extracting json response from document service.
=> HOCS-5224 bug fix for DocumentDTO

src/main/resources/processes/POGR/POGR_GRO.bpmn, src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn, src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_TRIAGE.java
There is currently no export from the POGR GRO Triage stage for an
internal transfer. This is causing the team not to be changing on the
next entry to this stage. This change amends this call to update
`DraftTeamUUID` and `DraftTeamName`.
This also amends the tests and activity to not be a `close` but a
`reject`.
=> HOCS-5391: fix internal gro team transfer

src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
Fix the addition of a case note at the POGR draft stage for both HMPO
and GRO. This includes correcting the field name to point to the correct
one on the screen and also changing the type in the BPMN to indicate
`CLOSE` rather than `Closed`.
=> HOCS-5433: fix draft case closure note

src/main/resources/processes/BF/BF_TRIAGE.bpmn, src/main/resources/processes/BF2/BF2_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/bf/BF_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/bf2/BF2_TRIAGE.java
If neither a 'Yes'/'No' value is passed to either the
`PaymentTypeConsolatory` or `PaymentTypeExGratia` at BF(2) Triage
but one is 'Yes' then a null exception is thrown by workflow. This
change reworks the expressions to have default flows to clear values and
also changes the 'Yes' expressions to be more readable.
=> HOCS-5456: fix BF triage payment null exception

src/main/resources/processes/POGR/POGR_GRO.bpmn, src/main/resources/processes/POGR/POGR_HMPO.bpmn, src/main/resources/processes/POGR2/POGR2.bpmn, src/main/resources/processes/POGR2/POGR2_GRO.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_DISPATCH.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_DRAFT.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_ESCALATE.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_INVESTIGATION.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_QA.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_DISPATCH.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_DRAFT.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_ESCALATE.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_INVESTIGATION.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_QA.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO.java
Add the base HMPO and GRO stage 2 flows to support ongoing development. This allows for multiple developers to work on individual stages while also ensuring that the team assignation is the same as Stage.
Blank Investigation, Draft, Escalation, QA and Dispatch stages have been added that should be updated as necessary. 
This also includes a minor cleanup of the HMPO and GRO Stage 1 flow to ensure default flows exist where necessary.
=> HOCS-4768: add base POGR stage 2 flow 

src/main/resources/screens/POGR2_GRO_DISPATCH_INPUT.json, src/main/resources/screens/POGR2_HMPO_DISPATCH_INPUT.json, src/main/resources/screens/POGR_GRO_DISPATCH_INPUT.json, src/main/resources/screens/POGR_HMPO_DISPATCH_INPUT.json
1. Currently POGR & POGR2 case type support complaint category and reason(s) as part of data input screen. On some occasions the complaint reason maybe incorrect after being investigated. 
2. In these circumstances the complaint reason must be updatable in the dispatch stage. 
3. This PR changes would help user to recorrect the complaint category and complaint reasons during dispatch stage. This will affect POGR HMPO, POGR GRO, POGR2 HMPO and POGR2 GRO case types.
=> Hocs 5617 confirm complaint reason

src/main/resources/screens/IEDET_DRAFT_INPUT.json
Change the document selection entity-list at IEDET Draft to only select draft documents. To allow for the `PRIMARY DRAFT` tag this change also changes the name to DraftDocuments for enrichment.
=> HOCS-5691: change draft document field

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/resources/processes/MPAM/MPAM.bpmn, src/main/resources/processes/MPAM/MPAM_TRIAGE_ESCALATED_REQUESTED_CONTRIBUTION.bpmn, src/main/resources/processes/MPAM/MPAM_TRIAGE_REQUESTED_CONTRIBUTION.bpmn
Removal of the unallocate user call from MPAM Triage Requested Contribution diagrams as unnecessary. This was from incorrect implementation initially and not required as the same user can be allocated to these cases.
=> HOCS-5696: remove unallocate call

src/main/resources/screens/MPAM_QA_CLEARANCE_INPUT.json
Remove the visible false flag from the `RequestSecretariatClearance` option in MPAM QA Clearance.
=> HOCS-3628: change choice visibility

src/main/resources/processes/MPAM/MPAM_TRIAGE.bpmn
After passing the initial user input screen in the MPAM_TRIAGE process there are 3 direction moves: `FORWARD`, `UpdateEnquirySubject`, and `UpdateRefType`. We currently don't handle a default flow out of this screen. This change makes the `FORWARD` route the default while we design best practice across processes.
=> Add missing default flow to MPAM_TRIAGE

src/main/resources/screens/PSU_TRAIGE_COMPLAINT.json
In the IEDET PSU Triage stage, the option 'No - send to team not on DECS' is instead showing as 'No - send to team not to DECS'
=> [HOCS-5883] Correct typo in PSU triage stage CloseCase option

src/main/resources/screens/IEDET_TRIAGE_CATEGORY.json
HOCS-5859 - This PR would help to fix the bug when 
user selects Provision for minors check box and 
click on submit button where user would be navigated 
complaint details screen. 
Currently if the user selects this option and clicks on 
submit button then an error is propagated which is an 
incorrect behaviour.
=> HOCS-5859 - Update correct label name for Provision for Minors checkbox

src/main/resources/processes/IEDET/IEDET.bpmn, src/main/resources/processes/PSU/PSU_IEDET_COMPLAINT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU_IEDET_COMPLAINT.java
Rename the `PSU_COMPLIANT` to `PSU_IEDET_COMPLAINT`. This makes it more clear what diagram is being called when we have multiple PSU integrations.
=> HOCS-5931: rename process name

src/main/resources/screens/live/COMP_REGISTRATION_INPUT.json, src/main/resources/screens/live/COMP_SERVICE_QA_INPUT.json, src/main/resources/screens/live/SMC_REGISTRATION_INPUT.json
Changed field labels to use sentence case for following screens:
- COMP_SERVICE_QA_INPUT
- COMP_REGISTRATION_INPUT
- SMC_REGISTRATION_INPUT
Have also updated fields to match in accordion and summary (see PR for hocs-casework)
=> HOCS-6170: UKVI and SMC content updates for registration and QA input

src/main/resources/processes/COMP/COMP_EXGRATIA.bpmn, src/main/resources/processes/COMP/COMP_EXGRATIA_TRIAGE.bpmn, src/main/resources/processes/COMP/COMP_MINORMISCONDUCT.bpmn, src/main/resources/processes/COMP/COMP_MINORMISCONDUCT_TRIAGE.bpmn, src/main/resources/processes/COMP/COMP_SERVICE.bpmn, src/main/resources/processes/COMP/COMP_SERVICE_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_EX_GRATIA_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_MINORMISCONDUCT_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_SERVICE_TRIAGE.java
This fixes the issue with comp cases going to the COMP_OTHER stage instead of PSU due to the CompType being unintentionally set to blank during triage
=> HOCS-6232: Fix COMP -> PSU escalation

src/main/resources/screens/live/DCU_ANSWERING.json, src/main/resources/screens/live/DCU_FAQ_ANSWERING.json
Add the `HomeSecReply` field to the associated screens to aid the simplification of tagging Home Secretary reply cases.
=> HOCS-4148: add HomeSecReply fields to screens

src/main/resources/screens/live/COMP_REGISTRATION_CATEGORY.json, src/main/resources/screens/live/SERVICE_CATEGORY.json
This change reworks the category screens to better fit user needs. This includes removing the OwningCSU field as its not required. It also includes reordering of checkboxes into alphabetical order to allow better visual scrolling.
=> HOCS-5824: change comp category screens

src/main/resources/screens/live/COMP_REGISTRATION_CATEGORY.json, src/main/resources/screens/live/EXGRATIA_CATEGORY.json, src/main/resources/screens/live/MM_CATEGORY.json, src/main/resources/screens/live/SERVICE_CATEGORY.json
Remove all the accordions from category screens as its not required and enforces more actions from the users. This change uses the checkbox group label instead.
=> HOCS-5838: refactor out accordion

src/main/resources/screens/live/COMP_SERVICE_TRIAGE_BUSAREA.json
Remove conditional choice logic around Owning CSU for COMP(2) cases as this was removed due to not being required under HOCS-5824.
=> HOCS-6542: remove conditional choice logic

src/main/resources/processes/DCU/DCU_MIN.bpmn, src/main/resources/processes/DCU/DCU_MIN_MINISTER_SIGN_OFF.bpmn, src/main/resources/screens/live/APPROVE_MINISTER_SIGN_OFF.json
HOCS-6199 broke backwards compatibility with existing cases on old live process versions. This change aims to re-add backwards compatibility into this flow and screens to allow these cases to progress.
The caveat is that cases created since the last release will have a small timeframe where `ACCEPT` won't work. As this option is for existing cases, they will be able to reselect the relevant new option.
=> HOCS-6550: support live cases ministerial sign off

src/main/resources/processes/COMP/COMP_EXGRATIA_TRIAGE.bpmn, src/main/resources/processes/COMP/COMP_MINORMISCONDUCT_TRIAGE.bpmn, src/main/resources/processes/COMP/COMP_SERVICE_TRIAGE.bpmn, src/main/resources/screens/live/COMP_SERVICE_TRIAGE_ACCEPT.json, src/main/resources/screens/live/EXGRATIA_TRIAGE_ACCEPT.json, src/main/resources/screens/live/MINORMISCONDUCT_TRIAGE_ACCEPT.json, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_EX_GRATIA_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_MINORMISCONDUCT_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_SERVICE_TRIAGE.java
The reject to CCH option had been set with the value CCH This broke existing cases as the old workflows expected a Yes/No value This change updates the CCH value to be no, so it becomes backwards compatible
=> Fix: Update COMP triage accept screens, reject option

build.gradle, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResource.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/GetProcessVariablesResponse.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/ProcessVariables.java, src/main/java/uk/gov/digital/ho/hocs/workflow/application/SpringConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClient.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResourceWebMvcTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClientTest.java
- Query variables in all processes associated with a case
- Query variables for a specific process
- Update variables for a specific process
- Adds `com.fasterxml.jackson.datatype:jackson-datatype-jdk` for handling (de)serialization of Optional
- - - -
The intent for this PR is to provide some http endpoints that can be used via hocs-toolbox to inspect and correct variables for a case. The usecase is to allow TO cases that have lost their teamUUID in [HOCS-6963](https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6963) to be investigated and corrected.
In my local environment I have been able to use this to break a case in a similar manner as the TO cases with the issue, see the same error, and update the ID to the expected value and see that allow the case to be progressed normally …
=> [HOCS-6963]  Add endpoints for process variables
