src/main/java/uk/gov/digital/ho/hocs/workflow/dto/WorkflowType.java
Exclusive of #6. Committed on behalf of @LCairns
=> Change WorkflowType schema

src/main/java/uk/gov/digital/ho/hocs/workflow/application/RequestData.java, src/main/java/uk/gov/digital/ho/hocs/workflow/domain/exception/ResourceExceptionHandler.java, src/main/resources/logback-spring.xml
=> Added catch all error handler

src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/AddressDto.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/CreateCaseworkCorrespondentRequest.java
keep compatibility with Casework service by introducing an AddressDTO.
=> keep compatibility with casework

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_REGISTRATION.bpmn
Initial Camunda for WCS. Currently uses a lot of DCU Dispatch for ending stage.
=> Create WCS case.

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_ELIGIBILITY.bpmn, src/main/resources/processes/WCS_REGISTRATION.bpmn
Merge WCS Eligibility into WCS main branch.
=> Camunda for Eligibility work flow.

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_QA.bpmn
New Camunda stage. Merging to WCS main branch.
=> Camunda for QA work flow.

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_DISPATCH.bpmn, src/main/resources/processes/WCS_PAYMENT.bpmn, src/main/resources/processes/WCS_RESPONSE.bpmn
Waiting for Tim to do the stories, so I've had to re-use the previous branch (the branch will get deleted when finished).
=> Camunda for Dispatch work flow.

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_ELIGIBILITY.bpmn, src/main/resources/processes/WCS_IDENTITY.bpmn, src/main/resources/processes/WCS_REGISTRATION.bpmn, src/main/resources/processes/WCS_TRIAGE.bpmn
All workflow "Step" stories up to and including Triage. Merge to WCS.
=> Business work flow implemented up to Triage.

src/main/resources/processes/WCS_DISPATCH.bpmn
Work flow for Dispatch stage. Merge to WCS.
=> Work flow for Dispatch stage.

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_COMPLETE.bpmn
Work flow for Complete stage. Merge to WCS.
=> Work flow for Complete stage.

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_REGISTRATION.bpmn
Identity stage moved within Registration stage. Merge to WCS.
=> HOCS-1265 : stage 1 identity check now performed by Registration team.

src/main/resources/processes/WCS_PAYMENT_CHECKLIST.bpmn
Payment work flow. Merge to WCS.
=> HOCS-1290 : Payment work flow

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_NIL_OFFER_REPLY.bpmn, src/main/resources/processes/WCS_OFFER_APPROVAL.bpmn, src/main/resources/processes/WCS_OFFER_REPLY.bpmn, src/main/resources/processes/WCS_PAYMENT_APPROVAL.bpmn, src/main/resources/processes/WCS_SEND_OFFER.bpmn, src/main/resources/processes/WCS_SEND_PAYMENT.bpmn
All the rest of the payments stuff. Merge to WCS.
=> HOCS-1290 : Payment work flow, all the rest

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_CASEWORK.bpmn, src/main/resources/processes/WCS_COMPLETE.bpmn, src/main/resources/processes/WCS_ELIGIBILITY.bpmn, src/main/resources/processes/WCS_IDENTITY.bpmn, src/main/resources/processes/WCS_NIL_OFFER_REPLY.bpmn, src/main/resources/processes/WCS_OFFER_APPROVAL.bpmn, src/main/resources/processes/WCS_OFFER_REPLY.bpmn, src/main/resources/processes/WCS_PAYMENT_APPROVAL.bpmn, src/main/resources/processes/WCS_PAYMENT_CHECKLIST.bpmn, src/main/resources/processes/WCS_QA.bpmn, src/main/resources/processes/WCS_REGISTRATION.bpmn, src/main/resources/processes/WCS_SEND_OFFER.bpmn, src/main/resources/processes/WCS_SEND_PAYMENT.bpmn, src/main/resources/processes/WCS_TIER1.bpmn, src/main/resources/processes/WCS_TIER2.bpmn
Make keys more human readable. Merge to WCS.
=> HOCS-1333 : readable keys

src/main/resources/processes/WCS.bpmn
PNC fail at "Payment Approval" stage goes to Casework, not QA. Merge to WCS.
=> HOCS-1345 : PNC fail at Payment Approval goes to casework

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_ELIGIBILITY.bpmn
Unchallenged nil payment closes the claim.
Also, remove redundant flow from Eligibility.
Merge to WCS.
=> HOCS-1348 : unchallenged nil payment closes the claim

src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_ELIGIBILITY_ON_HOLD.bpmn
When no response from claimant during Eligibility, close the claim. With Confirmation.
Merge to WCS.
=> HOCS-1152 : Eligibility on hold, no response

src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResource.java
Allow task force to upload docs; change create case to "owner" access level.
=> HOCS-1360 : task force team upload docs

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/resources/processes/WCS_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
Registration (task force) path changed. Eligibility automated. Merge to WCS.
=> HOCS-1372 : re-work registration

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/resources/processes/WCS.bpmn, src/main/resources/processes/WCS_CASEWORK_PRE.bpmn, src/main/resources/processes/WCS_ELIGIBILITY_PRE.bpmn, src/main/resources/processes/WCS_PAYMENT_PRE.bpmn, src/main/resources/processes/WCS_PAYMENT_PREP_PRE.bpmn, src/main/resources/processes/WCS_QA_PRE.bpmn, src/main/resources/processes/WCS_REGISTRATION_PRE.bpmn, src/main/resources/processes/WCS_TIER1_PRE.bpmn, src/main/resources/processes/WCS_TRIAGE_PRE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
Add pre-stages to clear down brought forward date when team changes.
=> HOCS-1298 : add brought forward date (clear between teams)

src/main/resources/processes/DCU_DTEN.bpmn, src/main/resources/processes/DCU_MIN.bpmn, src/main/resources/processes/DCU_TRO.bpmn
Change case route from PR to FAQ, fix for team allocation.
=> HOCS-1480 : change case route from PR to FAQ, fix for team

src/main/resources/processes/WCS_COMPLETE.bpmn
Confirmation page for closing a successfully completed claim.
=> HOCS-1461 : claim closure confirmation

src/main/resources/processes/WCS_TIER1.bpmn
Tier-1 outcome options have been reworded
=> HOCS-1502 : Tier-1 option rewording

src/main/resources/processes/DCU_DTEN.bpmn
Fix for DTEN to set the completed flag.
Old lines 8-9 remove incoming flows from "End Case".
New lines 250-251 add incoming flows (from NRN & OGD) into "Complete Case".
=> HOCS-1445 : Searching for active only cases returns completed cases

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java, src/main/resources/processes/UKVI_CREATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClientTest.java
Set different M-Ref deadline for whole Case lifetime, not per stage.
New endpoint to override SLA on Case deadline.
Merge to UKVI2.
=> HOCS-1581 : required by date for M-Ref cases

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/UpdateCaseworkTeamStageTextRequest.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/UpdateCaseworkTeamStageTextResponse.java, src/main/resources/processes/UKVI.bpmn, src/main/resources/processes/UKVI_CREATION.bpmn, src/main/resources/processes/UKVI_DRAFT.bpmn, src/main/resources/processes/UKVI_QA.bpmn, src/main/resources/processes/UKVI_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/UpdateCaseworkTeamStageTextRequestTest.java
New endpoint for BPMN to change Team based on "Text" link type.
Merge to UKVI2.
=> UKVI2 HOCS-1582 : correspondence cases are sent to correct workstack

src/main/resources/processes/UKVI_CREATION.bpmn
New page for adding correspondents.
=> HOCS-1690 : move "add correspondent" link to new page

src/main/resources/processes/UKVI_PO.bpmn
New page to capture rejection reason, calls "updateAllocationNote".
=> HOCS-1714 : reason textbox when rejecting at print for signage, fix

src/main/resources/processes/UKVI_PO.bpmn, src/main/resources/processes/UKVI_QA.bpmn
Added "Save changes" (Pending) options to QA and PO workflows.
=> HOCS-1715 : changes to field names

src/main/resources/processes/UKVI_PO.bpmn
New page for PO dispatch that prompts for actual date of dispatch.
=> HOCS-1723 : Private Office date dispatch moved to new page

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn
New gateway out of Draft Escalated to route case for closure.
=> HOCS-1742 : draft escalate stage can close a case

src/main/resources/processes/MPAM_QA_ESCALATE.bpmn
Additional steps at QA Escalated to prompt and save case note when closing.
=> HOCS-1743 : closing QA escalated case prompts for case note

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn
New page within Triage Escalate to prompt for explanation of case closure.
=> HOCS-1741 : cases at Triage Escalate stage can be closed

src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn
Direction check was placed after Validation check. Switched positions of the two gateway points in the flow. (Not a problem for Triage or QA - I checked.)
=> HOCS-1790 : Draft Escalate Close Case back link, fix

src/main/resources/processes/DCU_MIN_MARKUP.bpmn
Additional task in MIN PR/FAQ flow to change deadline when PO Team (or override team) is HO Sec.
=> HOCS-1798 : HO Sec signoff, 10 day main deadline

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/UpdateStageDeadlineRequest.java, src/main/resources/processes/DCU_MIN_MARKUP.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/CaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/UpdateStageDeadlineRequestTest.java
New endpoint to update a stage deadline of current case, pass thru to Casework.
=> HOCS-1799 : Home Secretary draft stage deadline

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DISPATCH.bpmn, src/main/resources/processes/MPAM_DISPATCHED_FOLLOW_UP.bpmn, src/main/resources/processes/MPAM_DRAFT_REQUESTED_CONTRIBUTION.bpmn, src/main/resources/processes/MPAM_PO.bpmn, src/main/resources/processes/MPAM_TRIAGE_REQUESTED_CONTRIBUTION.bpmn
- updated BMPN flows to include new flow paths for Dispatched - follow up stage
- request contribution stages now clear 'DueDate' rather than
'RequestContributionDeadline' due to shared variable.
=> HOCS-1828 - UKVI - Mark Bring Forward

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn
New flow in MPAM Triage to convert RefType to Official/Ministerial.
New flow in MPAM Draft to convert RefType to Official/Ministerial.
Incremental counter for each conversion.
=> HOCS-1773 : change case RefType

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn
Offer RefType & BusArea change mechanic at Triage (Escalated) and Draft (Escalated) stages.
=> HOCS-1849 : change bus area & ref type at escalate stages, fix

src/main/resources/processes/DCU_BASE_QA_RESPONSE.bpmn
Additional "MOIDFY" option from QA Response, and new screen for that option.
=> HOCS-1826 : QA Response can modify primary draft

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ON_HOLD.bpmn, src/main/resources/processes/MPAM_TRIAGE_REQUESTED_CONTRIBUTION.bpmn
- also including work for:
1878 - UKVI Campaign - Put into Campaign: Triage escalated
1879 - UKVI Campaign - Put into Campaign: Triage contribution requested
- added routes to Campaign stage within bmpn files.
=> HOCS-1877 - UKVI Campaign - Put into Campaign: Triage on hold

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_CAMPAIGN.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_DRAFT_ONHOLD.bpmn, src/main/resources/processes/MPAM_DRAFT_REQUESTED_CONTRIBUTION.bpmn
HOCS-1881 - UKVI Campaign - Put into Campaign: Draft on hold
HOCS-1882 - UKVI Campaign - Put into Campaign: Draft escalated
HOCS-1883 - UKVI Campaign - Put into Campaign: Draft contribution requested
- added routes to Campaign stage within bmpn files.
- fixed team mapping issues around Draft -> Campaign stages
=> HOCS-1880 - UKVI Campaign - Put into Campaign: Draft

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_QA.bpmn, src/main/resources/processes/MPAM_QA_ESCALATE.bpmn, src/main/resources/processes/MPAM_QA_ONHOLD.bpmn
HOCS-1885 - UKVI Campaign - Put into Campaign: QA on Hold
HOCS-1886 - UKVI Campaign - Put into Campaign: QA contribution requested
- added routes to Campaign stage within bmpn files. (QA stages)
=> HOCS-1884 - UKVI Campaign - Put into Campaign: QA

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DISPATCH.bpmn, src/main/resources/processes/MPAM_PO.bpmn
HOCS-1888 - UKVI Campaign - Put into Campaign: Dispatch
- added routes to Campaign stage within bmpn files. (dispatch and private office stages)
=> HOCS-1887 - UKVI Campaign - Put into Campaign: private office

src/main/resources/processes/DCU_BASE_QA_RESPONSE.bpmn, src/main/resources/processes/DCU_DTEN.bpmn, src/main/resources/processes/DCU_MIN.bpmn, src/main/resources/processes/DCU_TRO.bpmn
The "MODIFY" option now progresses forward to the next stage.
(Top level flow now needs to check for this returned value.)
=> HOCS-1826 : QA Response can modify primary draft documents, fix

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DISPATCH.bpmn
New route from Awaiting Dispatch back to Draft. New reason note screen.
=> HOCS-1919 : return case from awaiting dispatch back to draft

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DISPATCH.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn
Route back from Draft to Triage.
New screen to capture reason as case note.
Unallocate Triage user. Assign to new team.
=> HOCS-1918 : workflow route from Draft to Triage

.gitignore, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_QA.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn
Add the screens and links to the escalation to workflow manager screen for MPAM triage, draft and qa.
=> HOCS-1960: Add escalate reason screens to MPAM workflow

src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_QA_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn
When deleting cases that are duplicates after escalating, we no longer want to capture the reason for this.
=> HOCS-2025: remove stage for saving notes when deleting cases

src/main/resources/processes/MTS.bpmn, src/main/resources/processes/MTS_DATA_INPUT.bpmn, src/main/resources/processes/MTS_ON_HOLD.bpmn
Three new BPMN: top level MTS, plus Data Input and On Hold.
=> HOCS-2066 : MTS initial skeleton workflow for MPAM Telephone Surgery

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DISPATCH.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_QA.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn
Added updates to stages, Triage, Draft, QA and Dispatch to allow telephone operators to close cases early.
=> HOCS-2019 : add new bpmn diagram routing for early case closure.

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_CREATION.bpmn, src/main/resources/processes/MPAM_TRANSFER.bpmn
This PR modifies/creates the camunda flows necessary for the transfer case flow.
=> HOCS-2136: Transfer to OGD at MPAM Creation stage

build.gradle, src/main/resources/processes/DCU_MIN.bpmn, src/main/resources/processes/DCU_MIN_MINISTER_SIGN_OFF.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN_MinisterSignOff.java, src/test/java/uk/gov/digital/ho/hocs/workflow/util/CallActivityReturnVariable.java, src/test/java/uk/gov/digital/ho/hocs/workflow/util/ExecutionVariableSequence.java, src/test/resources/camunda.cfg.xml
Add a rejection step similar to "Not approved" but in this case go back to the PO sign-off stage.
=> HOCS-2266 : Return to private office stage from minister sign off.

src/main/resources/processes/MPAM.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java
As a result of MC the gateway path from Contribution Requested Escalation to PutInCampaign was wrong. Before we was doing an '&&' instead of a '||' resulting in a pathing issue for Camunda. This change fixes this and adds a test case to ensure no regression.
=> HOCS-2307: fix gateway condition to campaign

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_CREATION.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_TRANSFER.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn
Added the capability to alter the case due date, record notes and accept or reject a transferred case.
=> HOCS-2189 : add ability to update cases within transfer stage

src/main/resources/processes/DCU_MIN_MARKUP.bpmn, src/main/resources/processes/DCU_MIN_PRIVATE_OFFICE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN_MARKUP.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN_PRIVATE_OFFICE.java
* add steps to update deadlines for ministers/directors in markup
* add unit tests for DCU_MIN_MARKUP
=> HOCS-2193-Private Office Team target/deadline (Mark up)

src/integration-test/java/uk/gov/digital/ho/hocs/workflow/security/SecurityIntegrationTest.java, src/main/java/uk/gov/digital/ho/hocs/workflow/security/AccessLevel.java, src/main/java/uk/gov/digital/ho/hocs/workflow/security/AllocatedAspect.java, src/main/java/uk/gov/digital/ho/hocs/workflow/security/UserPermissionsService.java, src/main/resources/processes/DCU_MIN_MARKUP.bpmn, src/main/resources/processes/DCU_MIN_PRIVATE_OFFICE.bpmn, src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_CREATION.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRANSFER.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN_MARKUP.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN_PRIVATE_OFFICE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMCreation.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraft.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraftEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTransfer.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriage.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriageEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/security/AccessLevelTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/security/AllocatedAspectTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/security/UserPermissionsServiceTest.java
Moving case to Campaign from Triage or Draft clears Rejected status.
=> HOCS-2365 : PutOnCampaign clears Rejected status

src/main/resources/application-auto-deployment.properties, src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DRAFT.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMCommonTests.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraft.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraftEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriage.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriageEscalate.java
There are 6 locations for the screen 3 x triage and 3 x draft. In each case the output of the call activity nas been defaulted to "Confirm".
=> HOCS-1907 : Change MPAM workflow to remove the unsed Confirm and Save changes radio butons from the business area change screen.

src/test/java/uk/gov/digital/ho/hocs/workflow/processes/DCU_MIN.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java, src/test/java/uk/gov/digital/ho/hocs/workflow/util/CallActivityMockWrapper.java
Test utility to simplify callActivity mocking.
Refactored code to use new utility class.
=> HOCS-2375 - Wrap call activity mocks in a simpler interface.

src/main/resources/processes/MPAM_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraft.java
This work replaces activities removed in a recent merge activity. Also added some tests to ensure this does not happen again.
=> HOCS-2463 replace activities removed in merge

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/infoclient/InfoClient.java, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/infoclient/InfoClientTest.java
Create stage validates the provided user is in the provided team.
=> HOCS-2015 : When case converted then remove allocation if user not in new team

src/main/resources/processes/CMS_CREATION.bpmn
Additional screen for adding correspondents.
=> HOCS-2574 : add screen for correspondents

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATED_REQUESTED_CONTRIBUTION.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATED_REQUESTED_CONTRIBUTION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraftEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriageEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM_DRAFT_ESCALATED_REQUESTED_CONTRIBUTION.java
* Add request contribution activities to MPAM Triage Escalate and MPAM Draft Escalate workflows
=> HOCS-2311 Request contribution at escalated stage

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/GetCorrespondentResponse.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/GetCorrespondentsResponse.java, src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_CREATION.bpmn, src/main/resources/processes/COMP_SERVICE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
Workflow for CCH, placeholder for CCT Stage 1 Triage Service.
Merge to epic.
=> HOCS-2648 : CCH workflow

src/main/resources/processes/FOI.bpmn, src/main/resources/processes/FOI_DATA_INPUT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_Data_Input.java
This ticket implements the data input stage into the FOI camunda diagrams.
=> HOCS-2519 : add data input stage

src/main/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClient.java, src/main/resources/processes/FOI.bpmn, src/main/resources/processes/FOI_ALLOCATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_ALLOCATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_Data_Input.java
Includes new feature where Camunda form key is used to store the screen names. 
See https://collaboration.homeoffice.gov.uk/display/HOCS/Camunda+Improvements#CamundaImprovements-Usingformkeytostoretheformnames
=> HOCS-2326 FOI allocation stage

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_CCH_RETURNS.bpmn, src/main/resources/processes/COMP_CLOSED.bpmn, src/main/resources/processes/COMP_OTHER.bpmn, src/main/resources/processes/COMP_SERVICE_DRAFT.bpmn, src/main/resources/processes/COMP_SERVICE_QA.bpmn, src/main/resources/processes/COMP_SERVICE_RESP_DRAFT.bpmn, src/main/resources/processes/COMP_SERVICE_SEND.bpmn, src/main/resources/processes/COMP_SERVICE_TRIAGE.bpmn, src/main/resources/processes/COMP_SERVICE_WFM.bpmn
Stages for CCT workflow skeleton.
Merge to epic.
=> HOCS-2695 : CCT workflow

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_CCH_RETURNS.bpmn, src/main/resources/processes/COMP_CLOSED.bpmn, src/main/resources/processes/COMP_CREATION.bpmn, src/main/resources/processes/COMP_SERVICE_DRAFT.bpmn, src/main/resources/processes/COMP_SERVICE_QA.bpmn, src/main/resources/processes/COMP_SERVICE_TRIAGE.bpmn, src/main/resources/processes/COMP_SERVICE_WFM.bpmn
"Stage" value is set to "Stage1" during creation, changed to "Stage2" when a soft-closed case is re-opened.
Moving between stages selects the required team based on this "Stage" value.
Merge to epic.
=> HOCS-2716 : CCT Stage2 workflow

src/main/resources/processes/COMP.bpmn
New decision point to check if "IsTemplate" checkbox has been ticked ("TL"); if so, flows to CCT Response (Draft) stage, else continues to Triage.
Merge to epic.
=> HOCS-2739 : CCT "is template" cases skip Triage

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClient.java, src/main/resources/processes/FOI.bpmn, src/main/resources/processes/FOI_ACCEPTANCE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_ACCEPTANCE.java
* Update Camunda flows
* Update tests
=> HOCS-2753 User selects No at the acceptance stage

src/main/resources/processes/FOI.bpmn, src/main/resources/processes/FOI_ACCEPTANCE.bpmn, src/main/resources/processes/FOI_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_ACCEPTANCE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java
* Add new stage draft team acceptance stage
=> HOCS-2670 Draft team Acceptance (MVP)

src/main/resources/processes/FOI_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java
=> HOCS-2580 - Draft stage screens

src/main/resources/processes/COMP_CCH_RETURNS.bpmn, src/main/resources/processes/COMP_SERVICE_TRIAGE.bpmn
Flow for new CCT Triage screen. Added back button to (now) 2nd screen.
Also, fix defaulted sequence flow in CCH Returns.
Merge to epic.
=> HOCS-2913 : CCT business area and enquiry reason

src/main/resources/processes/FOI_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java
=> HOCS-2600 Response type and Exemptions

src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraftEscalate.java
Allow for the back button action on the 
`UserTask_RequestContributionInput` screen incase users 
mistakenly click to go down that path.
=> HOCS-2914 back button workflow handling

src/main/resources/processes/FOI_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java
A new 'Sensitivity' screen has been added, and all flow now route to the same 'Upload Draft' screen.
=> HOCS-2601 Sensitivity

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/application/CamundaProcessEngineConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClient.java, src/main/resources/processes/MPAM/MPAM_UPDATE_ENQUIRY_SUBJECT_REASON.bpmn, src/main/resources/processes/MPAM_DRAFT_ESCALATE.bpmn, src/main/resources/processes/MPAM_TRIAGE.bpmn, src/main/resources/processes/MPAM_TRIAGE_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/camundaclient/CamundaClientTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMCommonTests.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMDraftEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriage.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMTriageEscalate.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/mpam/MPAMUpdateEnquirySubjectReason.java
create feature branch from epic
merge main into feature branch
=> HOCS-2966 merge in main

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_MINOR_CHECK.bpmn, src/main/resources/processes/COMP_MINOR_RESP.bpmn
New workflows for Minor Misconduct: accept/reject, & response stages.
Merge into epic.
=> HOCS-2892 : Minor Misconduct workflow

src/main/resources/processes/FOI_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java
* Add placeholder allocation  activitites to FOI_DRAFT
=> HOCS-2983 Create high-level flow and placeholders for approval stages

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_SERVICE_DRAFT.bpmn, src/main/resources/processes/COMP_SERVICE_RESP_ESCALATE.bpmn
New stage for "Response Escalated".
New route from CCT Response back to CCT Triage.
Team allocations for these new routes.
Merge to epic.
=> HOCS-3029 : CCT Response team options: escalate, and return

src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP_CREATION.java
Add tests for `COMP_CREATION.bpmn`
=> HOCS-2778: Comp Creation tests

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_SERVICE_DRAFT.bpmn, src/main/resources/processes/COMP_SERVICE_ESCALATE.bpmn, src/main/resources/processes/COMP_SERVICE_TRIAGE.bpmn
Renamed "Response Escalate" to just "Escalate", which is now also used for Triage escalation.
Merge to epic.
=> HOCS-3028 : CCT Triage escalate to WFM

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_CCH_RETURNS.bpmn, src/main/resources/processes/COMP_CLOSED.bpmn
Removed the "re-opened" stage and team.
Reworded close option to "Complete" at Closed stage.
Changed soft close option to hard close "Complete" at Returned stage.
Reason and confirmation screens added for both hard close "Complete" routes.
Merge to epic.
=> HOCS-3025 : CCH hard close cases

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_CCH_RETURNS.bpmn, src/main/resources/processes/COMP_CLOSED.bpmn, src/main/resources/processes/COMP_SERVICE_TRIAGE.bpmn
Triage can close a case if no response is provided.
Merge to epic.
=> HOCS-3026 : CCT Triage complete case

src/main/resources/processes/COMP.bpmn
"Out" params on both Stages that change "Stage" variable.
Check for "Stage2" after CCT flow; direct to completion for "Stage2".
Merge to epic.
=> HOCS-3027 : CCT Stage 2 complete case

src/main/resources/processes/FOI.bpmn, src/main/resources/processes/FOI_DRAFT.bpmn, src/main/resources/processes/FOI_QA.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_QA.java
* Fix y/n text issue
* Add QA stage and g6/g7 approval flow
=> HOCS-3003 FOI Q.A stage (G6/G7 Approval) MVP

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_REGISTRATION.bpmn, src/main/resources/processes/COMP_SERVICE_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP_REGISTRATION.java
Routing changes around escalation.
Finished renaming "Creation" to "Registration".
Merge to epic.
=> HOCS-3076 : CCT requested changes

src/main/resources/processes/COMP.bpmn, src/main/resources/processes/COMP_SERVICE_QA.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP_SERVICE_QA.java
Unit test coverage for COMP_SERVICE_QA, and CCT Response QA workstacks (Stages 1 & 2).
I've also renamed "QaResult" to "CctQaResult" to avoid conflicts with any future QA stages.
Merge to epic.
=> HOCS-2782 : COMP service QA unit tests

src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP_SERVICE_SEND.java
Single step flow.
Merge to epic.
=> HOCS-2784 : covering unit test for COMP_SERVICE_SEND

src/main/resources/processes/COMP.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP.java
Unit test coverage for top level COMP.bpmn workflow.
I've renamed some tasks away from the auto-generated random strings.
Also includes just a single unit test for Minor, which hasn't been agreed yet.
Merge to epic.
=> HOCS-2775 : COMP unit tests

src/main/resources/processes/MTS.bpmn, src/main/resources/processes/MTS_DATA_INPUT.bpmn, src/main/resources/processes/WCS.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/mts/MTS.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/mts/MTS_DATA_INPUT.java
=> Merge main into COMP epic.

src/main/resources/processes/FOI_DATA_INPUT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_Data_Input.java
* Automatically allocate FOI cases to their creator when the data input stage is entered
=> HOCS-3098 FOI Auto allocation of case at Data Input

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/resources/processes/FOI.bpmn, src/main/resources/processes/FOI_DISPATCH.bpmn, src/main/resources/processes/FOI_SOFT_CLOSE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DISPATCH.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_SOFT_CLOSE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/util/ExecutionVariableSequence.java
* Add Dispatch stage to FOI
* Add Soft Close Stage to FOI
=> HOCS-2545 FOI Dispatch (MVP)

src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/BpmnServiceTest.java
Fix to the date format of dateOfResponse field which was causing rendering issues in frontend.
=> HOCS-3010 fix to bpmn service date format

src/main/resources/processes/FOI_DRAFT.bpmn
* Fix Back conditions at two broken draft stages
=> HOCS-3357 Back button not working

src/main/resources/processes/FOI_DATA_INPUT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DATA_INPUT.java
Added a step to add the primary topic to the current case in the FOI Data Input stage
=> HOCS-3251 save foi topic in data input stage

src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/FieldDto.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/FieldDtoBuilder.java, src/main/java/uk/gov/digital/ho/hocs/workflow/domain/model/forms/HocsFormField.java, src/main/resources/processes/FOI_ACCEPTANCE.bpmn, src/main/resources/processes/FOI_CASE_CREATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java
HOCS-3287 Check your answers screen
* Add check your answers screen to creation stage
=> HOCS-3287 Check your answers screen

src/main/resources/processes/FOI_CASE_CREATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_CASE_CREATION.java
* Update the case deadline when the received date is update in the creatio…n stage
=> Update case deadline

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_PO.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMPo.java
Send MPAM PO Rejected cases back to QA rather than Draft for UKVI/BF/IE
=> HOCS-3394 MPAM PO Rejected cases return to QA Ministerial workstack

src/main/resources/processes/FOI_CASE_CREATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_CASE_CREATION.java
added a back link to the FOI Validity check screen.
=> HOCS-3549 add back link to validity screen

src/main/resources/processes/FOI.bpmn, src/main/resources/processes/FOI_ALLOCATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_ALLOCATION.java
Updates the allocation stage, removing the Request Type Selection screen, removing the Allocation Case Note entry field and adding in a confirmation screen displaying the team name and case number.
=> HOCS 3417 Allocate a case

src/main/resources/processes/DCU_BASE_DATA_INPUT.bpmn
There are differences between the screens now so this makes them separate rather than sharing
=> HOCS-3622 Split DCU MIN and DCU TRO Input screens

src/main/resources/processes/FOI_ALLOCATION.bpmn
1) Remove green "Case has been allocated to:..." panel from final screen in Allocation stage
2) Black text in screen shot to change from "Case FOI/xxxx... has been allocated to..." to "Case FOI/xxxx... will be allocated to..."
3) Green button to read "Confirm allocation"
=> HOCS-3262 Changes to final allocation screen

src/main/resources/processes/MPAM/MPAM_UPDATE_ENQUIRY_SUBJECT_REASON.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/mpam/MPAMUpdateEnquirySubjectReason.java
There is a request to add an Enquiry Reason of EU National 
Compliance Measures to the Person Specific enquiry subject. This 
new reason should then divert to a new screen that allows for 
further input. To ensure that the data stays correct when this is 
changed, further activities have been added to update the data and 
clear out where necessary.
=> HOCS-3464: eu national enquiry reason

src/main/resources/processes/FOI_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DRAFT.java
Added missing logic to draft stage bpmn diagram for back link.
=> HOCS-3647 add logic to draft bpmn diagram for back link

src/main/resources/processes/COMP.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/COMP.java
This change allows the user to hard close a case from the EG/MM triage step
=> HOCS-3711 Allow hard closing from Ex-Gratia & Minor Misconduct Triage Contributions

src/main/resources/processes/FOI_DISPATCH.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/FOI_DISPATCH.java
* Skip to dispatch confirmation on full release
=> HOCS-3758 Capture Outcomes and Exemptions: Information released in full

src/main/resources/processes/MPAM.bpmn, src/main/resources/processes/MPAM_QA_CLEARANCE_REQ.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAM.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMQaClearanceRequest.java
This PR alters workflow to use the new variable name for the radio buttons on the clearance fulfilment screen that was setup in the associated data PR
=> HOCS-3771 making selection of mpam clearance request status mandatory

build.gradle, src/main/resources/processes/COMP2_REGISTRATION.bpmn, src/test/diffs/COMP_CCH_REOPENED-COMP2_CCH_REOPENED.diff, src/test/diffs/COMP_CCH_RETURNS-COMP2_CCH_RETURNS.diff, src/test/diffs/COMP_CLOSED-COMP2_CLOSED.diff, src/test/diffs/COMP_EXGRATIA_ESCALATE-COMP2_EXGRATIA_ESCALATE.diff, src/test/diffs/COMP_EXGRATIA_QA-COMP2_EXGRATIA_QA.diff, src/test/diffs/COMP_EXGRATIA_RESPONSE_DRAFT-COMP2_EXGRATIA_RESPONSE_DRAFT.diff, src/test/diffs/COMP_EXGRATIA_SEND-COMP2_EXGRATIA_SEND.diff, src/test/diffs/COMP_EXGRATIA_TRIAGE-COMP2_EXGRATIA_TRIAGE.diff, src/test/diffs/COMP_MINORMISCONDUCT_ESCALATE-COMP2_MINORMISCONDUCT_ESCALATE.diff, src/test/diffs/COMP_MINORMISCONDUCT_QA-COMP2_MINORMISCONDUCT_QA.diff, src/test/diffs/COMP_MINORMISCONDUCT_RESPONSE_DRAFT-COMP2_MINORMISCONDUCT_RESPONSE_DRAFT.diff, src/test/diffs/COMP_MINORMISCONDUCT_SEND-COMP2_MINORMISCONDUCT_SEND.diff, src/test/diffs/COMP_MINORMISCONDUCT_TRIAGE-COMP2_MINORMISCONDUCT_TRIAGE.diff, src/test/diffs/COMP_MINOR_CHECK-COMP2_MINOR_CHECK.diff, src/test/diffs/COMP_MINOR_RESP-COMP2_MINOR_RESP.diff, src/test/diffs/COMP_OTHER-COMP2_OTHER.diff, src/test/diffs/COMP_REGISTRATION-COMP2_REGISTRATION.diff, src/test/diffs/COMP_SERVICE_DRAFT-COMP2_SERVICE_DRAFT.diff, src/test/diffs/COMP_SERVICE_ESCALATE-COMP2_SERVICE_ESCALATE.diff, src/test/diffs/COMP_SERVICE_QA-COMP2_SERVICE_QA.diff, src/test/diffs/COMP_SERVICE_SEND-COMP2_SERVICE_SEND.diff, src/test/diffs/COMP_SERVICE_TRIAGE-COMP2_SERVICE_TRIAGE.diff, src/test/scripts/check_COMP_COMP2.sh, src/test/scripts/diff_COMP_COMP2.sh
Add a test to ensure we have checked and confirmed the differences between COMP & COMP2 BPMN files
=> HOCS-3780 - Add diff based test for COMP bpmn files

src/main/resources/processes/MPAM_QA_CLEARANCE_REQ.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/MPAMQaClearanceRequest.java
Update the `Rejected` case data value to `By QA` when rejected from
the `QA (Secretariat Clearance Requested)` stage. This is then used in 
the workstack to identify where the case has been rejected from.
=> HOCS-3777: update rejected column value

src/main/resources/processes/FOI_ACCEPTANCE.bpmn, src/main/resources/processes/FOI_ALLOCATION.bpmn, src/main/resources/processes/FOI_DISPATCH.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/foi/FOI_ACCEPTANCE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/foi/FOI_ALLOCATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/foi/FOI_DISPATCH.java
=> HOCS-3903 - Some eligible pages in FOI workflow do not have back link.

src/main/resources/processes/COMP2_MINORMISCONDUCT_TRIAGE.bpmn, src/main/resources/processes/COMP_MINORMISCONDUCT_TRIAGE.bpmn
Fix Minor Misconduct business contribution type to be CCT_BUS_CONTRIB
=> HOCS-3983 Minor Misconduct bus contribution somu type

src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResource.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/CreateDocumentRequest.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/documentclient/DocumentClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/documentclient/dto/CreateCaseworkDocumentRequest.java, src/main/java/uk/gov/digital/ho/hocs/workflow/migration/MigrationWorkflowService.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/workflow/client/documentclient/DocumentClientTest.java
* Allow documents to be tied to an action data item
=> HOCS-3884 Add document upload to appeals

src/main/resources/processes/TO.bpmn, src/main/resources/processes/TO_DATA_INPUT.bpmn, src/main/resources/processes/TO_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_DATA_INPUT.java
This delivers the data input stage for treat official cases.
=> HOCS-4121 added data input stage for treat official

build.gradle, src/integration-test/resources/application.properties, src/main/java/uk/gov/digital/ho/hocs/workflow/application/RequestData.java, src/main/resources/application.properties
Remove Camel libs from the project, they are unused.
=> HOCS-3954 Remove Camel

build.gradle
This reverts commit 0180602c6810ce817fb295edb928217da80966ad.
=> Dependabot: Revert "Bump camunda-bom from 7.9.0 to 7.16.0 (#585)"

src/main/resources/processes/TO.bpmn, src/main/resources/processes/TO_CAMPAIGN.bpmn, src/main/resources/processes/TO_DRAFT.bpmn, src/main/resources/processes/TO_QA.bpmn, src/main/resources/processes/TO_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_CAMPAIGN.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_QA.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_TRIAGE.java
* Allow TO cases to be moved to a campaign
=> HOCS-4134 Campaigns

src/main/resources/processes/TO.bpmn, src/main/resources/processes/TO_QA.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_QA.java
* add required workflow paths for QA change business area
=> HOCS-4454 Change business area link broken at QA stage

src/main/resources/processes/TO.bpmn, src/main/resources/processes/TO_CAMPAIGN.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_CAMPAIGN.java
* Fix save condition predicate
=> HOCS-4471 Save changes actions broken at Campaign stage

src/main/resources/processes/TO_DATA_INPUT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_DATA_INPUT.java
Removed the option of selecting a Member of Parliament for a Recipient in Treat Official work flow.
=> HOCS-4461 remove mp selection from recipient list

src/main/resources/processes/TO_DATA_INPUT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/to/TO_DATA_INPUT.java
Fixes the back link behaviour from TO Correspondent Details to
Data Input stage.
=> HOCS-4583 Fix Back link from TO Correspondent Details

src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowResource.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/application/LogEvent.java, src/main/java/uk/gov/digital/ho/hocs/workflow/util/NoteType.java, src/test/java/uk/gov/digital/ho/hocs/workflow/api/WorkflowServiceTest.java
Adds RequestParam for type when updating case data
=> HOCS-4578 Case data type request param

src/main/resources/processes/POGR/POGR.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR.java
Creation of the basic POGR workflow that supports the opening of a case
and immediate closure.
=> HOCS-4599: create blank POGR workflow

src/main/resources/processes/POGR/POGR.bpmn, src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Add the workflow that supports HMPO/GRO cases being assigned to one of
them.
=> HOCS-4627: workflow for business area assigning

src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Workflow process for supporting sending of interim letter within
`POGR_REGISTRATION`.
=> HOCS-4631: support sending interim letter

src/main/resources/processes/POGR/POGR_GRO.bpmn, src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn, src/main/resources/processes/POGR/POGR_HMPO.bpmn, src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_TRIAGE.java
Add the flow for the triage acceptance flow for HMPO and GRO. Initially
they both use the same flow - there are small nuanced changes to the
handling as GRO has internal transfer to other DECS teams.
=> HOCS-4633: POGR triage acceptance

src/main/resources/processes/POGR/GRO/POGR_GRO_PRIORITY_CHANGE_SCREEN.bpmn, src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_PRIORITY_CHANGE_SCREEN.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
New camunda process for handling screens that support priority change at
a screen. This currently updates the priority depending on the changed
value. 5 days for non priority - 1 days for priority.
=> HOCS-4630: support priority change

src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn, src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_TRIAGE.java
Add the Investigation process flow for POGR HMPO/GRO.
=> HOCS-4634: add Investigation process flow

src/main/resources/processes/POGR/POGR_GRO.bpmn, src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn, src/main/resources/processes/POGR/POGR_HMPO.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
Camunda flow and tests for the POGR draft process.
=> HOCS-4636: POGR draft stage

src/main/resources/processes/POGR/POGR_GRO.bpmn, src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_GRO_TRIAGE.bpmn, src/main/resources/processes/POGR/POGR_HMPO.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_TRIAGE.bpmn, src/main/resources/processes/POGR/SHARED/POGR_TELEPHONE_RESPONSE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_TELEPHONE_RESPONSE.java
The flow for handling telephone responses at the POGR draft stages.
Generic process for both business areas that is called and creates a
case note within the system if a telephone response is utilised. This
then bubbles up to the top process for the business area which handles
the closure.
=> HOCS-4635: POGR telephone response flow

src/main/java/uk/gov/digital/ho/hocs/workflow/client/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/workflow/security/AllocatedAspect.java, src/test/java/uk/gov/digital/ho/hocs/workflow/security/AllocatedAspectTest.java
Hocs-3976: remove call causing case viewed audits when not needed
=> HOCS-3976: remove case viewed audits

src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
Addition of a draft stage rejection note.
=> HOCS-5246 added reject note to draft stage

src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_GRO_QA.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_QA.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_QA.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_QA.java
On rejection to Draft from QA - a Rejected case attribute with value
'By QA' is saved. To ensure this is correct - this value is cleared on
completion on Draft stages.
=> HOCS-4656: add POGR Rejected service tasks

src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java
HOCS-4943 for POGR - Closing the case @ Draft State
1. DML changes to add Close the case radio button
2. Add Close Reason drop down values
3. Creation of new screen - with label, inset, text area, Complete case and back button
4. Respective test cases were created.
Opening this PR after closing - https://github.com/UKHomeOffice/hocs-workflow/pull/744
=> HOCS-4943: support draft case closure 

src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java
Remove backwards functionality from the POGR registration stage as
no longer required.
=> HOCS-5363: remove POGR registration backwards func

src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn
On the POGR Registration screen if the business area is GRO then we set
the correct investigatory team at the end of the flow. This currently
points to POGR_GRO_TRIAGE whereas it should point to
POGR_GRO_INVESTIGATION.
=> HOCS-5471: correct team look up

src/main/resources/processes/POGR/POGR_GRO.bpmn, src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_GRO_INVESTIGATION.bpmn, src/main/resources/processes/POGR/POGR_HMPO.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_INVESTIGATION.bpmn, src/main/resources/processes/POGR/SHARED/POGR_CLOSE_CASE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_CLOSE_CASE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_INVESTIGATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_INVESTIGATION.java
Rework of the case closure mechanic for POGR workflow. This change
includes pulling the case closure into a generic process that is called
by HMPO and GRO Draft/Investigation screens.
=> HOCS-5469: rework case closure

src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/main/resources/processes/POGR2/POGR2_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_REGISTRATION.java
Add the HMPO Data Input screen and associated flows to
POGR2_REGISTRATION.
Also includes the following improvements: 
- Add default flows for when DIRECTION is not forward and backward 
to flow in line with current best practice.
=> HOCS-5025: add HMPO data input process

src/main/resources/processes/POGR/GRO/POGR_GRO_PRIORITY_CHANGE_SCREEN.bpmn, src/main/resources/processes/POGR/POGR_REGISTRATION.bpmn, src/main/resources/processes/POGR2/POGR2_REGISTRATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_GRO_PRIORITY_CHANGE_SCREEN.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_REGISTRATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_REGISTRATION.java
Add the GRO Data Input screen and associated flows to
POGR2_REGISTRATION.
This change also includes a refactoring of how the deadline days are
updated. These are now embedded within the
POGR_GRO_PRIORITY_CHANGE_SCREEN to give increased flexibility.
=> HOCS-5029: add POGR2 GRO Data Input

src/main/resources/processes/POGR/POGR_GRO_INVESTIGATION.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_INVESTIGATION.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_INVESTIGATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_INVESTIGATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_INVESTIGATION.java
Add the necessary flow for POGR2 Stage 2 Acceptance at the Investigation
stage.
Improve the GRO Investigation stage by removing the unnecessary
CloseCaseInvestigation out property and update the CloseCase output
property.
=> HOCS-5034: add and update POGR investigation

src/main/resources/processes/POGR/POGR_HMPO_INVESTIGATION.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_INVESTIGATION.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_INVESTIGATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_INVESTIGATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_INVESTIGATION.java
Add the POGR2 Stage 2 implementation of the Investigation stage. This
effectively mimics the stage 1 version.
=> HOCS-5035: add POGR Stage 2 Investigation

src/main/resources/processes/POGR/POGR_GRO_DRAFT.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DRAFT.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_DRAFT.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_DRAFT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_DRAFT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_DRAFT.java
Add the POGR2 Stage 2 implementation of the Draft stage. This
effectively mimics the stage 1 version apart from not having the
Telephone Response at present.
=> HOCS-5039: add POGR2 Draft process

src/main/resources/processes/POGR/POGR_GRO_DISPATCH.bpmn, src/main/resources/processes/POGR/POGR_HMPO_DISPATCH.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_DISPATCH.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_DISPATCH.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_DISPATCH.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_DISPATCH.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_DISPATCH.java
Add the POGR2 Stage 2 implementation of the Dispatch.
Additionally, this change adds a default flow if/when the DIRECTION out
of the activity is not 'FORWARD'.
=> HOCS-5043: add Stage 2 dispatch

src/main/resources/processes/POGR/POGR_GRO_ESCALATE.bpmn, src/main/resources/processes/POGR/POGR_HMPO_ESCALATE.bpmn, src/main/resources/processes/POGR2/POGR2_GRO_ESCALATE.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_ESCALATE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_GRO_ESCALATE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_ESCALATE.java
Add the POGR2 Stage 2 implementation for Escalation.
=> HOCS-5526: add Stage 2 escalation process

src/main/resources/processes/POGR/POGR_HMPO_INVESTIGATION.bpmn, src/main/resources/processes/POGR2/POGR2_HMPO_INVESTIGATION.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_HMPO_INVESTIGATION.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr2/POGR2_HMPO_INVESTIGATION.java
Update the expression for HMPO POGR Investigation rejection to ensure
that the CaseNote_InvestigationReject is populated.
=> HOCS-5547: update expression

src/main/resources/processes/POGR/SHARED/POGR_TELEPHONE_RESPONSE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/pogr/POGR_TELEPHONE_RESPONSE.java
Add missing back flow to the POGR_TELEPHONE_RESPONSE diagram that
doesn't call the case note creation service task.
=> HOCS-5571: add back flow

src/main/java/uk/gov/digital/ho/hocs/workflow/domain/repositories/ScreenRepository.java, src/main/resources/processes/MPAM/MPAM_UPDATE_ENQUIRY_SUBJECT_REASON.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/domain/repositories/ScreenRepositoryTest.java
Removes extra space after MPAM_ENQUIRY_REASON_EU_NATIONAL_DETAILS
=> HOCS-5707 Remove extra space after form ID

src/main/resources/screens/IEDET_TRIAGE_DETAILS_NOT_SERIOUS.json, src/main/resources/screens/IEDET_TRIAGE_DETAILS_SERIOUS.json
JIRA Link : https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-5662
=> HOCS-5662 : IEDET - Complaint Details screen sentence case changes

src/main/resources/screens/live/COMP_REGISTRATION_COMPLAINANT.json
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-5694
=> [HOCS-5694] Remove gender radios from complainant details

src/main/resources/processes/IEDET/IEDET.bpmn, src/main/resources/processes/IEDET/IEDET_PSU_OUTCOME.bpmn, src/main/resources/processes/IEDET/IEDET_PSU_REGISTRATION.bpmn, src/main/resources/processes/IEDET/IEDET_PSU_TRIAGE.bpmn, src/main/resources/processes/PSU/PSU.bpmn, src/main/resources/processes/PSU/PSU_IEDET_COMPLAINT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_PSU_OUTCOME.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/iedet/IEDET_PSU_TRIAGE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU_IEDET_COMPLAINT.java
Improve the IEDET workflows through implementing the following changes:
- Change variable handling to use `getVariable` and `hasVariable`
- Change ReturnCase service tasks to be within screen variables
- Move the ReturnCase functionality to top level flow.
=> HOCS-5423: improve IEDET workflows

src/main/resources/screens/live/COMP2_ORIGINATION_CHECK.json
HOCS-6163- Correcting Complaint spelling in Stage2 COMP phase.
=> HOCS-6153- correct Complaint spelling in COMP stage2 phase

src/main/resources/processes/PSU/PSU_COMP2_COMPLAINT.bpmn, src/main/resources/processes/PSU/PSU_COMP_COMPLAINT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU_COMP_COMPLAINT.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-5666
=> HOCS-5666 - Add "Rejected by PSU" tag

src/main/resources/processes/COMP/COMP_PSU_OUTCOME.bpmn, src/main/resources/processes/COMP2/COMP2_PSU_OUTCOME.bpmn, src/main/resources/processes/PSU/PSU_COMP2_COMPLAINT.bpmn, src/main/resources/processes/PSU/PSU_COMP_COMPLAINT.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_PSU_OUTCOME.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/psu/PSU_COMP_COMPLAINT.java
HOCS-5732- Currently SLA by default is set to
20 working days. This PR would help to update SLA
to 60 working days when case is accepted by PSU and
when it's moved to PSU outcome stage. When the user
reject this case and send it back to UKVI - then
SLA would be updated to 20 working days. Changes
are covered using BPMN changes similar to IEDET
to PSU workflow stages.
=> HOCS-5732- syncing changes from master

src/main/resources/processes/COMP/COMP.bpmn, src/main/resources/processes/COMP/COMP_CCH.bpmn, src/main/resources/processes/COMP/COMP_CCH_RETURNS.bpmn, src/main/resources/processes/COMP/COMP_EXGRATIA.bpmn, src/main/resources/processes/COMP/COMP_MINORMISCONDUCT.bpmn, src/main/resources/processes/COMP/COMP_MINOR_MISCONDUCT_CHECK.bpmn, src/main/resources/processes/COMP/COMP_SERVICE.bpmn, src/main/resources/processes/COMP2/COMP2.bpmn, src/main/resources/processes/COMP2/COMP2_CCH.bpmn, src/main/resources/processes/COMP2/COMP2_EXGRATIA.bpmn, src/main/resources/processes/COMP2/COMP2_MINORMISCONDUCT.bpmn, src/main/resources/processes/COMP2/COMP2_SERVICE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_CCH.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_EXGRATIA.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_MINORMISCONDUCT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_SERVICE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp2/COMP2.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp2/COMP2_EXGRATIA.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp2/COMP2_MINORMISCONDUCT.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp2/COMP2_SERVICE.java
Rework the BPMN diagrams for COMP and COMP2 so that each of Service, Ex-Gratia, Minor Misconduct, and CCH are extracted into their own diagram.
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6152
=> [HOCS-6152] refactor comp workflow

src/main/resources/processes/BF/BF_RECATEGORISE.bpmn, src/main/resources/processes/COMP/COMP_RECATEGORISE.bpmn, src/main/resources/processes/COMP2/COMP2_RECATEGORISE.bpmn, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/bf/BF_RECATEGORISE.java, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/comp/COMP_RECATEGORISE.java
This fixes the failing recategorisation which is caused by the `Stage` variable being empty
=> HOCS-6214: Fix failing recategorisations from PSU

src/main/resources/screens/live/IEDET_DRAFT_INPUT.json
PR changes to include IEDET draft complaint response UI improvements.
=> HOCS-6188-IEDET draft complaint response UI improvements

src/main/resources/screens/live/IEDET_SEND_INPUT.json
This PR changes would include UI improvements for record case response
screen.
=> HOCS-6189:UI improvements for record case response

src/main/resources/screens/live/WCS_PAYMENT_PREP_INPUT.json
Fix the WCS_PAYMENT_PREP_INPUT screen by correcting the invalid JSON.
=> HOCS-6278: fix invalid screen json

src/main/resources/screens/live/IEDET_SEND_INPUT.json
HOCS-6189: This PR would like to help update Substantiated 
label to substantiated for IEDET case type.
=> HOCS-6189:Modify Partially substantiated label

src/main/resources/processes/BF/BF_REGISTRATION.bpmn, src/main/resources/screens/live/BF_REGISTRATION_COMPLAINANT.json, src/test/java/uk/gov/digital/ho/hocs/workflow/processes/bf/BF_REGISTRATION.java
HOCS-5886:This PR would help to create BF based 
BF input registration page so that it gets separated
from COMP registration json page. Corresponding 
BPMN changes made to adjust the flow for Service &
Minor Misconduct as the following complaint details
page is removed.
=> Hocs 5886 complaint details screen changes

src/main/resources/screens/live/EXGRATIA_CATEGORY.json
This change reworks the category screens to better fit user needs.
=> HOCS-5836: change comp category screens

build.gradle, src/main/resources/screens/live/WCS_ARCH_ELIGIBILITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_ARCH_IDENTITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_CASEWORK_HOLD.json, src/main/resources/screens/live/WCS_CASEWORK_INPUT.json, src/main/resources/screens/live/WCS_CASEWORK_INPUT2.json, src/main/resources/screens/live/WCS_COMPLETE_CLAIM.json, src/main/resources/screens/live/WCS_ELIGIBILITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_ELIG_HOLD.json, src/main/resources/screens/live/WCS_ELIG_IDPASS_CHECK.json, src/main/resources/screens/live/WCS_IDENTITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_ID_CHECK_NTF.json, src/main/resources/screens/live/WCS_NIL_OFFER_REPLY_INPUT.json, src/main/resources/screens/live/WCS_OFFER_APPROVAL_INPUT.json, src/main/resources/screens/live/WCS_OFFER_REPLY_INPUT.json, src/main/resources/screens/live/WCS_PAYMENT_APPROVAL_INPUT.json, src/main/resources/screens/live/WCS_PAYMENT_CHECKLIST_INPUT.json, src/main/resources/screens/live/WCS_PAYMENT_PREP_INPUT.json, src/main/resources/screens/live/WCS_QA_INPUT.json, src/main/resources/screens/live/WCS_REG_ID_CHECK_NTF.json, src/main/resources/screens/live/WCS_REG_ID_CHECK_TF.json, src/main/resources/screens/live/WCS_SEND_OFFER_INPUT.json, src/main/resources/screens/live/WCS_SEND_PAYMENT_INPUT.json, src/main/resources/screens/live/WCS_T1_REVIEW_ELIGIBILITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_T1_REVIEW_IDENTITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_TIER1_AWAIT.json, src/main/resources/screens/live/WCS_TIER1_INPUT.json, src/main/resources/screens/live/WCS_TIER2_COORD.json, src/main/resources/screens/live/WCS_TRIAGE_CW_TEAM.json
Added new brought forward reasons and sorted the list into alphabetical order as required.
Performed a search for the 'Brought forward' field in hocs-workflow and seemed to be a total of 28 screens where this needed changing.
=> HOCS-6511: WCS add brought forward reasons

src/main/resources/screens/live/COMP_SERVICE_TRIAGE_CASE_DETAILS.json
Change to follow the GDS style guide for sentence case.
=> HOCS-5825: sentence case

src/main/resources/screens/live/COMP_SERVICE_TRIAGE_BUSAREA.json, src/main/resources/screens/live/COMP_TRIAGE_BUSAREA.json
Change to follow the GDS style guide for sentence case.
=> HOCS-5827: sentence case

src/main/resources/screens/live/COMP_OTHER_INPUT.json, src/main/resources/screens/live/COMP_REGISTRATION_INPUT.json, src/main/resources/screens/live/EXGRATIA_CATEGORY.json, src/main/resources/screens/ukvi-psu/COMP_REGISTRATION_DETAILS_SERIOUS.json
Applies the following fixes: 
* Correct primary action label on screen
* Sentence case field values
=> HOCS-5836/HOCS-6565/HOCS-6563: apply multiple bug fixes

src/main/resources/screens/live/COMP_SERVICE_TRIAGE_BUSAREA.json
This reverts commit 57d35a790f4bb19bc4e9c3f187899aabec3bd387.
=> Revert "HOCS-6588 : COMP - Directorate selection (#1013)"

src/main/resources/screens/live/WCS_ARCH_ELIGIBILITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_ARCH_IDENTITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_CASEWORK_HOLD.json, src/main/resources/screens/live/WCS_CASEWORK_INPUT.json, src/main/resources/screens/live/WCS_CASEWORK_INPUT2.json, src/main/resources/screens/live/WCS_COMPLETE_CLAIM.json, src/main/resources/screens/live/WCS_ELIGIBILITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_ELIG_HOLD.json, src/main/resources/screens/live/WCS_ELIG_IDPASS_CHECK.json, src/main/resources/screens/live/WCS_IDENTITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_ID_CHECK_NTF.json, src/main/resources/screens/live/WCS_NIL_OFFER_REPLY_INPUT.json, src/main/resources/screens/live/WCS_OFFER_APPROVAL_INPUT.json, src/main/resources/screens/live/WCS_OFFER_REPLY_INPUT.json, src/main/resources/screens/live/WCS_PAYMENT_APPROVAL_INPUT.json, src/main/resources/screens/live/WCS_PAYMENT_CHECKLIST_INPUT.json, src/main/resources/screens/live/WCS_PAYMENT_PREP_INPUT.json, src/main/resources/screens/live/WCS_QA_INPUT.json, src/main/resources/screens/live/WCS_REG_ID_CHECK_NTF.json, src/main/resources/screens/live/WCS_REG_ID_CHECK_TF.json, src/main/resources/screens/live/WCS_SEND_OFFER_INPUT.json, src/main/resources/screens/live/WCS_SEND_PAYMENT_INPUT.json, src/main/resources/screens/live/WCS_T1_REVIEW_ELIGIBILITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_T1_REVIEW_IDENTITY_REJECTED_SC.json, src/main/resources/screens/live/WCS_TIER1_AWAIT.json, src/main/resources/screens/live/WCS_TIER1_INPUT.json, src/main/resources/screens/live/WCS_TIER2_COORD.json, src/main/resources/screens/live/WCS_TRIAGE_CW_TEAM.json
HOCS-6666: This PR would help to add additional check
box named Work in Progress for Brought forward option.
=> HOCS-6666:Changes for adding BF_WorkInProgress checkbox option

src/main/resources/screens/live/COMP_REGISTRATION_CATEGORY.json, src/main/resources/screens/live/COMP_REGISTRATION_CATEGORY_SERIOUS.json, src/main/resources/screens/live/EXGRATIA_CATEGORY.json, src/main/resources/screens/live/MM_CATEGORY.json, src/main/resources/screens/live/SERVICE_CATEGORY.json
Reverts UKHomeOffice/hocs-workflow#1043
=> Revert "HOCS-6756: Reinstate owning CSU field"

src/main/resources/screens/live/COMP_REGISTRATION_DETAILS_SERIOUS.json, src/main/resources/screens/live/COMP_REGISTRATION_INPUT.json, src/main/resources/screens/live/EXGRATIA_REGISTRATION_INPUT.json
HOCS-6793: Add REP to external contractor options. Tested both
workflow which display these options, summary, accordion and extracts 
were generated to test this scenario.
=> HOCS-6793: Add REP to external contractor options

src/main/resources/screens/live/COMP_SERVICE_TRIAGE_BUSAREA.json
HOCS-6791:Build changes for adding new UKVI COMP/COMP2 directorate and
respective business areas. This PR will make workflow with new directorate 
and business areas along with updated Other business areas entity lists.
=> Hocs 6791 update directorate bus area ukvi

src/main/resources/screens/live/COMP_SERVICE_TRIAGE_BUSAREA.json
HOCS-6810: Remove Border force options from new UKVI directorates changes.
=> HOCS-6810:Remove Border force options from new UKVI directorates changes

build.gradle, src/main/java/uk/gov/digital/ho/hocs/workflow/BpmnService.java, src/main/java/uk/gov/digital/ho/hocs/workflow/HocsWorkflowApplication.java, src/main/java/uk/gov/digital/ho/hocs/workflow/api/dto/CreateCaseworkCorrespondentRequest.java, src/main/java/uk/gov/digital/ho/hocs/workflow/application/LocalDateAttributeConverter.java, src/main/java/uk/gov/digital/ho/hocs/workflow/application/LocalDateTimeAttributeConverter.java, src/main/java/uk/gov/digital/ho/hocs/workflow/application/RequestData.java, src/main/java/uk/gov/digital/ho/hocs/workflow/client/caseworkclient/dto/CreateCaseNoteRequest.java, src/main/java/uk/gov/digital/ho/hocs/workflow/domain/exception/RestResponseEntityExceptionHandler.java, src/test/java/uk/gov/digital/ho/hocs/workflow/security/SecurityIntegrationTest.java
1) HOCS-6854:Build changes for spring boot 3.1.5 upgrade
2) Among 908 tests - 1 test case is failing (uk.gov.digital.ho.hocs.workflow.security.SecurityIntegrationTest#shouldReturnUnauthorisedForCreateCaseWhenUserIsNotInGroup) which needs more debugging. Added work around to resolve test case failure and below links has details:
https://github.com/spring-projects/spring-framework/issues/21321
=> HOCS-6854:Build changes for spring boot 3.1.5 upgrade

src/main/resources/screens/live/BF2_TRIAGE_TRANSFER.json, src/main/resources/screens/live/BF_TRIAGE_TRANSFER.json
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-4984
- Removed the identified hidden elements from both BF and BF2. 
- No use of component on page.
- No other instances found.
=> Removed unused hidden elements from BF and BF2
